### ISSUE TITLE
Make sprint points facultative

### ISSUE THREAD

**Issue by dereckson** [wmde/phragile#100]
Sprints' stories nowadays tend to be liberated from the idea to assign points to them.

Currently, there are several sprints on the Wikimedia Phabricator instance with every story at 0 point.

As such, Phragile should work in Phabricator instance deciding not to create a custom field to note points they aren't going to use.

**Comment by tobijat** [comment]
A solution would be to default to 1 for all tasks with no points. That would basically mean the graph shows you how many tasks have been closed or are still remaining in the sprint instead of relying on storypoints.

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100187
