### ISSUE TITLE
Burnup charts

### ISSUE THREAD

**Issue by awjrichards** [wmde/phragile#101]
* For background on why we strongly prefer burnup charts, especially for timespans longer than one sprint, see: http://brodzinski.com/2012/10/burn-up-better-burn-down.html
* NOTE: Should use historical estimates, as well as historical statuses
 * For all the tasks that had been resolved as of that day sum the estimates as they appeared on that day
 * To clarify: Phragile will have to step through the transaction history, to be able to accurately know that "As of date X, the sum of estimates of tasks in the project was Y"
 * (The Phabricator burndown report uses Task date created, which is not sufficient. We need to know when the task was added to the project)
* Must include tasks which used to be in the sprint, but no longer are, and exclude tasks which had not yet been added to that project
 * For each day being plotted, phragile needs to know all of the tasks that were in this project on that day
* MAY NEED API EXTENSION (to expose project transactions), or maybe it's OK to exclude tasks which have been removed from the projects
 * Sprint extension can expose more stuff via the API

**Comment by awjrichards** [comment]
Note this was copied from http://etherpad.wikimedia.org/p/Phragile-requirements-2015-05

**Comment by awjrichards** [comment]
This is a 'must have' for the WMF

**Comment by tobijat** [comment]
Just to understand it correctly: the burnup chart would be an inverse burndown chart while the scope line described in https://github.com/wmde/phragile/issues/102 would indicate tasks that were added or removed during the sprint. If that is correct, burnup charts can be realized by only looking at task transactions while it would be necessary to look at project transactions to get the full scope line.

Does it make sense to have the burnup without the scope line? Without having access to project transactions the scope line would only indicate if tasks were added during a sprint but not if tasks got removed. @awjrichards Can you also ask Kevin about that?

**Comment by awjrichards** [comment]
@tobijat no, it does not make sense to have the burnup without the scope line. i think the daily sprint snapshots mentioned in #103 could be a reasonable work around. i will follow up with Kevin :)

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100186
