### ISSUE TITLE
Calculate scope line based on points in the sprint at that time 

### ISSUE THREAD

**Issue by awjrichards** [wmde/phragile#102]
* NOTE: Must use the historical estimates, as well as historical statuses
 *Need to sum the estimates of all the tasks as they appeared on that day
* Must include tasks which used to be in the sprint, but no longer are, and exclude tasks which had not yet been added to that project
 *For each day being plotted, phragile needs to know all of the tasks that were in this project on that day
* Need a rule to handle unestimated tasks (TBD)
 *Could be a user-entered constant, or could be a calculated average
* SAME ISSUE ABOUT TASKS NO LONGER IN PROJECT; otherwise not hard

**Comment by awjrichards** [comment]
Note this was copied from http://etherpad.wikimedia.org/p/Phragile-requirements-2015-05

**Comment by awjrichards** [comment]
This is a 'must have' for the WMF

**Comment by tobijat** [comment]
Alternative solution to that would be daily sprint-snapshots as mentioned in https://github.com/wmde/phragile/issues/103#issuecomment-104899986.

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100185
