### ISSUE TITLE
For deployment: subset of app that only requires anonymous access

### ISSUE THREAD

**Issue by awjrichards** [wmde/phragile#105]
* Would prefer subset of the app which only does anonymous queries 
 * For increased security and easier deployment
 * CAN"T ACCESS SPRINT START/END DATE VIA API (would need to expose it, which is possible)

Note this is a 'nice to have' for the WMF; copied from http://etherpad.wikimedia.org/p/Phragile-requirements-2015-05

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100182
