### ISSUE TITLE
For deployment: subset of app that does not require its own database

### ISSUE THREAD

**Issue by awjrichards** [wmde/phragile#106]
* Would prefer subset of the app that doesn't require its own database 
 * For simpler deployment and less ongoing maintenance
 * Only feature to drop would be snapshots?
  *Needs to store phab ids of projects, but wouldn't if it had a page where you would just pass the project you want to graph along with the date range.

Note this is a 'nice to have' for the WMF; copied from http://etherpad.wikimedia.org/p/Phragile-requirements-2015-05

**Comment by tobijat** [comment]
Moved to https://phabricator.wikimedia.org/T100180
