### ISSUE TITLE
Set up code coverage CI

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/phragile#59]
Right now there is no automated CI. The main pain point I'm seeing is that right now reviewers or contributors that want to run the tests need to set up a working installation themselves, which involves some hassle.

**Comment by JeroenDeDauw** [comment]
I've enabled both TravisCI and ScrutinizerCI for the project.

https://travis-ci.org/wmde/phragile
https://scrutinizer-ci.com/g/wmde/phragile/

Code coverage is not set up yet, as this requires more work. See https://scrutinizer-ci.com/g/wmde/phragile/inspections/f8ae1f8e-f687-4f40-b5c5-c8f50ea31f81

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100198
