### ISSUE TITLE
Support "is-sprint" field in Phabricator projects

### ISSUE THREAD

**Issue by tobijat** [wmde/phragile#73]
Phabricator considers a project as a sprint if the "is-sprint" field is set. Phragile needs to set this field when it creates new sprint projects.

**Comment by tobijat** [comment]
As far as I understand, this is currently not possible due to limitations of the conduit API in Phabricator. Correct?

**Comment by tobijat** [comment]
Is there also no other possibility to set this field in an additional API request?

**Comment by jakobw** [comment]
No, projects only have 2 API methods: `project.create` and `project.query`.

**Comment by christopher-johnson** [comment]
Since the "is-sprint" field is created by the Sprint extension, the solution to this is probably to add a Conduit method within it.  There could also be a method to set the beginning and end dates.

**Comment by christopher-johnson** [comment]
Pushed patch to Gerrit here:  https://gerrit.wikimedia.org/r/#/c/201894/2
It seems to work.  Please review and I will merge it for testing on phab08.

**Comment by jakobw** [comment]
Using the `sprint.create` method implemented by Christopher would solve this problem, however, it would also create a dependency on the Sprint Extension. A solution would be to have this configurable for Phragile so that it uses `sprint.create` if the respective Phabricator instance includes the Sprint Extension and `project.create` if it doesn't.

**Comment by tobijat** [comment]
We could also try using sprint.create by default and fall back to project.create if that fails. What do you think? Adding a setting for this could be done later if we think it is really necessary.

**Comment by jakobw** [comment]
Good point. That would work too.

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100195
