### ISSUE TITLE
[install] We run into the Composer GitHub API limit

### ISSUE THREAD

**Issue by dereckson** [wmde/phragile#97]
When installing phragile, we run into the GitHub API limit of 60 requests per hour described in https://github.com/composer/composer/issues/1861

First pass of composer install is incomplete (vendor/laravel empty for example).

Second pass requires to create an auth token on GitHub (and so requires a GitHub account):

```
app@2e1755236b2d:/opt/phragile$ composer update  
Loading composer repositories with package information  
Updating dependencies (including require-dev)  
  - Installing laravel/framework (v5.0.31)  
    Downloading: Connecting...  
Could not fetch https://api.github.com/repos/laravel/framework/zipball/db0a7400465df159ba8c6eaa954f97f50bc19687, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+2e1755236b2d+2015-05-15+2137  
to retrieve a token. It will be stored in "/usr/local/app/.composer/auth.json" for future use by Composer.  
Token (hidden):     
Token stored successfully.  
    Downloading: 100%
```

This could complicate automated installation through Salt and has corrupted the build of my Docker image.

**Comment by jakobw** [comment]
`composer install` and `composer update` run without problems for me and so far I didn't hit the API limitations but I understand that it can be a problem. The issue you mentioned suggests to use `--prefer-source`. Does that do the trick?
Let me know if I can help!

**Comment by tobijat** [comment]
@dereckson the way @jakobw described should solve this issue.
