### ISSUE TITLE
[install] [doc] Better document the steps to be done on Phabricator to integrate with Phragile

### ISSUE THREAD

**Issue by dereckson** [wmde/phragile#98]
Currently, the documentation explains well the OAuth part to do in Phabricator.

The documentation should also cover the additional points:
* A summary. What assumptions Phragile does regarding Phabricator?
* Create a project-as-a-tag to mark tasks in review state (but see #99)
* Add a custom field in Maniphest (but see #100)

**Comment by jakobw** [comment]
Thanks for the feedback! Yes, some general documentation is still missing. We'll definitely consider this in the next development sprint.

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100190
