### ISSUE TITLE
Review state should be more flexible

### ISSUE THREAD

**Issue by dereckson** [wmde/phragile#99]
Currently, Phragile does the assertion a task has progressed and awaits review is it's tagged "to review". A tag in Phabricator is a project used as such, and for example, on Wikimedia Phabricator the *patch-for-review* tag is used. Then, this project's PHID is set in preferences as REVIEW_TAG_PHID.

**A board story**

If there is a goal to make Phragile more generic, this assertion of the existence of a review project-as-a-tag becomes a little strange, as the more natural way in a Sprint to indicate a task has progressed from one state to another is to move it in a workboard to the new state column (here a Pending review/For review/Review column).

Of course, this is blocked by [an upstream issue](https://secure.phabricator.com/T5523), as Phabricator doesn't currently expose in the API workboads (this is very annoying for our workflows, I wanted to be able get a list of tasks in a *To deploy* column to prepare the output to copy/paste in the Wikitech deployment page and had to write [a scraper](https://github.com/dereckson/wikimedia-config-todeploy/blob/master/src/PhabricatorBoardScraper.php) to temporarily achieve this).

**For pure Phabricator installs**

More simply, Phragile could imply a task is in review state if there is a Differential review attached to it, still open.

**Comment by jakobw** [comment]
Phragile lets you choose whether you want to use the status field for statuses or workboard columns for your projects. With the latter getting the "review" status will work as you described it.
The current implementation looks at the tasks' transactions to find out which column it has been moved to and then looks up the column's PHID to find out its name.

Differential support is also planned #29

**Comment by tobijat** [comment]
@dereckson does @jakobw's answer solve your question?

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100188
